---
title: "Massachusetts Town Explorer"
format: html
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, warnings = FALSE, include = FALSE}

knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE
)

options(scipen = 9999) 

source("libraries.R")
Sys.getenv("MAPBOX_PUBLIC_TOKEN")

# Realtor API (only 30 calls here)
# api_key <- Sys.getenv("RAPIDAPI_KEY")
# api_host <- "realtor.p.rapidapi.com"

```

# MCAS data

```{r include = FALSE}

mcas <- read_csv("data/MCAS_Achievement_Results_20250415.csv") %>%
  filter(
    SY == 2024,
    STUGRP == "White",
    ORG_NAME != "State",
    TEST_GRADE == "10",
    ORG_TYPE == "Public School District"
  ) %>%
  select(
    SY:STUGRP, STU_CNT, E_CNT, AVG_SCALED_SCORE
  )

mcas_agg <- mcas %>%
  group_by(DIST_NAME) %>%
  summarize(
    stu_cnt = median(STU_CNT),
    exceed_cnt = round(weighted.mean(E_CNT, w = STU_CNT), 0),
    avg_score = round(weighted.mean(AVG_SCALED_SCORE, w = STU_CNT), 0)
  ) %>%
  mutate(
    exceed_perct = round(exceed_cnt / stu_cnt, 3),
    school_size_est = stu_cnt*4,
    exceed_mcas_percentile = round(percent_rank(exceed_perct)*100,1)
  )

```

# Zillow data

```{r}

three_bed_home_price_zil <- read_csv("data/City_zhvi_bdrmcnt_3_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv") %>%
  filter(State == "MA") %>%
  select(RegionName, State, CountyName, last_col(offset = 12), last_col()) %>%
  mutate(one_year_price_change = round((`3/31/2025` - `3/31/2024`) / `3/31/2024` * 100, 1))

tracts_town_names <- tracts_map %>%
  as_tibble() %>%
  select(town_name) %>%
  distinct() %>% 
  arrange(town_name)

zillow_town_names <- three_bed_home_price_zil %>%
  select(RegionName) %>% 
  distinct() %>% 
  arrange(RegionName)

zillow_town_names1 <- zillow_town_names %>% 
  fuzzyjoin::stringdist_left_join(
    y = tracts_town_names,
    by = c("RegionName" = "town_name"),
    ignore_case = TRUE, 
    method = "jw",
    max_dist = 2, 
    distance_col = "dist"
  ) %>% 
  arrange((dist))

mapping <- read_csv("data/Mapping_Table_of_RegionName_to_MatchedTownName.csv")


```

# ACS Census Tract Data

```{r pull census data, include = FALSE}

options(tigris_use_cache = TRUE)

tracts <- get_acs(
  geography = "tract",
  variables = c(
    hh_income = "B19013_001"
    #med_home_value = "B25077_001"
  ),
  state = "MA",
  geometry = TRUE,
  year = 2023
)

```

```{r quality index, include = FALSE}

tracts_wide <- tracts %>%
  mutate(
    county = str_match(NAME, ";\\s*([^;]+?)\\s*;")[, 2]
  ) %>%
  relocate(county, .after = GEOID) %>%
  pivot_wider(
    names_from = variable,
    values_from = c(estimate, moe)
  ) %>%
  group_by(county) %>%
  mutate(NAME = str_extract(NAME, "^[^;]+\\s*"))

# Group by county and merge geometries
county_borders <- tracts_wide %>%
  group_by(county) %>%
  summarize(geometry = st_union(geometry)) %>%
  ungroup() %>%
  st_as_sf() %>% 
  ungroup()

county_borders <- st_transform(county_borders, crs = 4326)

# Instead of places(), use county subdivisions:
towns <- tigris::county_subdivisions(state = "MA", cb = TRUE, year = 2023) %>%
  st_transform(crs = st_crs(tracts))

# Spatial join: assign town names to each tract
tracts_with_towns <- st_join(tracts, towns["NAME"]) %>% 
  rename(tract_name = NAME.x,
         town_name = NAME.y) %>% 
  group_by(GEOID) %>% 
  mutate(count_grp = n()) %>% 
  relocate(count_grp)

# Join derived values back into tract-town data
tracts_map <- tracts_with_towns %>%
  left_join(
    tracts_wide %>% st_drop_geometry(), 
    by = "GEOID"
  ) %>% 
  ungroup()

tracts_map <- st_as_sf(tracts_map)
tracts_map <- st_transform(tracts_map, crs = 4326)

```

## School District mapping 

```{r include = FALSE}

town_school_dist_xwalk <- read_xlsx("data/final_school_districts_mapping_v1.xlsx") %>%
  distinct() %>%
  arrange(town_name) %>%
  group_by(town_name) %>%
  slice(1)

```

```{r include = FALSE}

tracts_map1 <- tracts_map %>% 
  left_join(
    town_school_dist_xwalk,
    by = "town_name") %>% 
  left_join(
    mcas_agg,
    by = "DIST_NAME"
  ) %>% 
  mutate(
    income_perctile = percent_rank(estimate_hh_income),
    raw_quality_index = .4*income_perctile + .6*exceed_mcas_percentile, 
    quality_index = rescale(raw_quality_index, to = c(0, 1))
  )

# na_dist <- tracts_map1 %>% 
#   filter(is.na(DIST_NAME))

```

# Generate Mapbox map

```{r, echo = FALSE}

leaflet(tracts_map1) %>%
  addMapboxTiles(
    style_id = "streets-v11",
    username = "mapbox"
  ) %>%
  addPolygons(
    fillColor = ~ifelse(quality_index >= 0.8, "#ffc107", "transparent"),
    fillOpacity = 0.2,
    color = "black",
    weight = 1,
    popup = ~paste0(
#      "<strong>Tract:</strong> ", NAME, "<br/>",
      "<strong>Town:</strong> ", town_name, "<br/>",      
      "<strong>County:</strong> ", county, "<br/>",
      "<strong>School District:</strong> ", DIST_NAME, "<br/>",      
      "<strong>Household Median Income:</strong> $", 
      formatC(estimate_hh_income, format = "f", digits = 0, big.mark = ","), 
      " (", round(income_perctile * 100), "th ptile)<br/>",
      "<strong>School Size:</strong> ", school_size_est, "<br/>",
      "<strong>MCAS Percentile:</strong> ", 
        ifelse(is.na(exceed_mcas_percentile), "NA", paste0(exceed_mcas_percentile, "%")), "<br/>",      
      "<strong>Overall quality score:</strong> ", round(quality_index * 100, 1), "%"
    )
  ) %>% 
  addPolygons(
    data = county_borders,
    fill = FALSE,
    color = "black",
    weight = 2,
    opacity = 1
  )


```

```{r include = FALSE}

# School quality score: 
# 
# MCAS standardized scores (DONE) 
# 
# Graduation rates
# 
# School expenditure per student



```

```{=html}

<hr style="margin-top:30px;">
<p style="text-align:center; font-size:14px; color:gray;">
  🐧 Built by <strong>DJ</strong> · 
  <a href="https://github.com/dal211/projects" target="_blank">GitHub</a> · 
  Data: Census ACS, DESE, Mapbox
</p>

```
